"""change availability to boolean

Revision ID: 0d0e4a9d1d1d
Revises: f88b2c83cb9f
Create Date: 2023-10-18 11:21:32.933686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0e4a9d1d1d'
down_revision = 'f88b2c83cb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
