"""fix

Revision ID: 256dcea0613b
Revises: 98aca64f4784
Create Date: 2023-10-17 09:50:17.625393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256dcea0613b'
down_revision = '98aca64f4784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
