"""bool on timeslots fix second

Revision ID: 2ade6f750bc5
Revises: 8a80fdadaea1
Create Date: 2023-10-18 14:21:58.076486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ade6f750bc5'
down_revision = '8a80fdadaea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeSlots', sa.Column('availability', sa.Boolean(), nullable=True))
    op.drop_column('timeSlots', 'availabilit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeSlots', sa.Column('availabilit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('timeSlots', 'availability')
    # ### end Alembic commands ###
