"""add appointment_association table 

Revision ID: 3bceb1bc732c
Revises: 0d0e4a9d1d1d
Create Date: 2023-10-18 14:02:55.521207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bceb1bc732c'
down_revision = '0d0e4a9d1d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
