"""Add trigger to update timeslot availability

Revision ID: 6bdd0505bf8a
Revises: 7f4dcb34ba5b
Create Date: 2023-10-26 16:01:13.597377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdd0505bf8a'
down_revision = '7f4dcb34ba5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
