"""add start_time end_time in locations table 

Revision ID: 7f4dcb34ba5b
Revises: 2ade6f750bc5
Create Date: 2023-10-20 11:40:13.931082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4dcb34ba5b'
down_revision = '2ade6f750bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('start_time', sa.String, nullable=True))
    op.add_column('locations', sa.Column('end_time', sa.String, nullable=True))
    op.drop_column('locations', 'opening_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('opening_hours', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('locations', 'end_time')
    op.drop_column('locations', 'start_time')
    # ### end Alembic commands ###
