"""bool on timeslots fix

Revision ID: 8a80fdadaea1
Revises: 648d6d146c97
Create Date: 2023-10-18 14:08:49.766099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a80fdadaea1'
down_revision = '648d6d146c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
