"""add start time and end time to TimeSlot Table 

Revision ID: f88b2c83cb9f
Revises: 5d0210d7e250
Create Date: 2023-10-18 10:46:59.171681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f88b2c83cb9f'
down_revision = '5d0210d7e250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeSlots', sa.Column('start_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('timeSlots', sa.Column('end_time', sa.TIMESTAMP(), nullable=True))
    op.drop_column('timeSlots', 'slot_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeSlots', sa.Column('slot_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('timeSlots', 'end_time')
    op.drop_column('timeSlots', 'start_time')
    # ### end Alembic commands ###
